"""
West Wing Annotation Workflow Script

This script automates the full annotation workflow so that multiple
team members can annotate without overlap, using Git as the shared
record of what's been done.

FIRST-TIME SETUP (one time only):
    1. Run: label-studio start
    2. Create an account in your browser
    3. Go to Account & Settings (icon in top-right corner)
    4. Copy your "Access Token"
    5. Close Label Studio (Ctrl+C in terminal)
    6. Run: python annotate.py setup
       (it will ask you to paste your token and enter your name)

EVERY TIME YOU ANNOTATE:
    1. Run: python annotate.py start
       (pulls from git, filters out already-annotated docs, opens Label Studio)
    2. Annotate in your browser
    3. When done, run: python annotate.py finish
       (exports your work, saves to shared file, commits and pushes)

That's it!
"""

import json
import os
import sys
import subprocess
import time
import random
import urllib.request
import urllib.error

# ── Configuration ──────────────────────────────────────────────
CONFIG_FILE = ".annotate_config.json"       # local, git-ignored
SHARED_ANNOTATIONS = "annotations/all_annotations.json"  # committed to git
TASKS_SOURCE = "label_studio_tasks.json"    # generated by prepare_for_label_studio.py
LS_URL = "http://localhost:8080"
PROJECT_NAME = "West Wing Power Dynamics"
BATCH_SIZE = 150  # how many fresh docs to load per session
RANDOM_SEED_BASE = 42
# ───────────────────────────────────────────────────────────────


def load_config():
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            return json.load(f)
    return {}


def save_config(config):
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=2)


def api_request(path, method="GET", data=None, token=None):
    """Make a request to the Label Studio API."""
    url = f"{LS_URL}/api{path}"
    headers = {
        "Authorization": f"Token {token}",
        "Content-Type": "application/json",
    }
    body = json.dumps(data).encode('utf-8') if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8') if e.fp else ''
        print(f"  API error {e.code}: {error_body[:200]}")
        return None
    except urllib.error.URLError:
        return None


def ls_is_running(token):
    """Check if Label Studio is running and token works."""
    result = api_request("/projects/", token=token)
    return result is not None


def start_label_studio():
    """Start Label Studio in the background."""
    print("  Starting Label Studio...")
    process = subprocess.Popen(
        ["label-studio", "start", "--no-browser"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    # Wait for it to boot
    for i in range(30):
        time.sleep(2)
        try:
            urllib.request.urlopen(f"{LS_URL}/health")
            print("  Label Studio is running.")
            return process
        except Exception:
            if i % 5 == 4:
                print("  Still waiting for Label Studio to start...")
    print("  ERROR: Label Studio didn't start in time.")
    print("  Try running 'label-studio start' manually in another terminal,")
    print("  then run 'python annotate.py start' again.")
    sys.exit(1)


def git_pull():
    """Pull latest from git."""
    print("  Pulling latest from git...")
    result = subprocess.run(["git", "pull"], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  WARNING: git pull had issues: {result.stderr.strip()}")
        print("  Continuing anyway...")
    else:
        print("  Git pull successful.")


def git_push(annotator_name):
    """Add, commit, and push annotations."""
    print("  Committing and pushing to git...")
    subprocess.run(["git", "add", SHARED_ANNOTATIONS], capture_output=True)
    msg = f"Add annotations from {annotator_name}"
    result = subprocess.run(["git", "commit", "-m", msg], capture_output=True, text=True)
    if "nothing to commit" in result.stdout:
        print("  No new annotations to commit.")
        return
    result = subprocess.run(["git", "push"], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  WARNING: git push failed: {result.stderr.strip()}")
        print("  You may need to pull first and try again.")
    else:
        print("  Pushed successfully.")


def load_already_annotated():
    """Load doc_ids that have already been annotated by anyone."""
    if not os.path.exists(SHARED_ANNOTATIONS):
        return set()
    with open(SHARED_ANNOTATIONS, 'r', encoding='utf-8') as f:
        annotations = json.load(f)
    return {a['doc_id'] for a in annotations}


def save_annotations(new_annotations):
    """Merge new annotations into the shared file."""
    os.makedirs(os.path.dirname(SHARED_ANNOTATIONS), exist_ok=True)
    existing = []
    if os.path.exists(SHARED_ANNOTATIONS):
        with open(SHARED_ANNOTATIONS, 'r', encoding='utf-8') as f:
            existing = json.load(f)

    existing.extend(new_annotations)
    with open(SHARED_ANNOTATIONS, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)

    return len(existing)


def find_or_create_project(token):
    """Find existing project or create a new one."""
    projects = api_request("/projects/", token=token)
    if projects and 'results' in projects:
        for p in projects['results']:
            if p['title'] == PROJECT_NAME:
                return p['id']

    # Read the labeling config
    config_path = "label_studio_config.xml"
    if not os.path.exists(config_path):
        print(f"  ERROR: {config_path} not found in project root.")
        print("  Make sure label_studio_config.xml is in your repo.")
        sys.exit(1)

    with open(config_path, 'r') as f:
        label_config = f.read()

    project = api_request("/projects/", method="POST", data={
        "title": PROJECT_NAME,
        "label_config": label_config,
    }, token=token)

    if project and 'id' in project:
        print(f"  Created new project: {PROJECT_NAME}")
        return project['id']

    print("  ERROR: Could not create project.")
    sys.exit(1)


def import_tasks(project_id, tasks, token):
    """Import tasks into the Label Studio project."""
    # Clear existing tasks first
    api_request(
        f"/projects/{project_id}/tasks/bulk-delete",
        method="POST",
        data={"type": "all"},
        token=token,
    )
    time.sleep(1)

    # Import new batch
    result = api_request(
        f"/projects/{project_id}/import",
        method="POST",
        data=tasks,
        token=token,
    )
    return result


def export_annotations(project_id, token):
    """Export all annotations from the current project."""
    result = api_request(
        f"/projects/{project_id}/export?exportType=JSON",
        token=token,
    )
    return result if result else []


def parse_ls_annotation(task):
    """Convert a Label Studio export task into our simplified format."""
    data = task.get('data', {})
    annotations = task.get('annotations', [])

    if not annotations:
        return None

    # Use the most recent annotation
    latest = annotations[-1]
    results = latest.get('result', [])

    parsed = {
        'doc_id': data.get('doc_id', ''),
        'episode': data.get('episode', ''),
        'character_a': data.get('character_a', ''),
        'character_b': data.get('character_b', ''),
        'pair_instance': data.get('pair_instance', ''),
        'excerpt': data.get('excerpt', ''),
        'annotator': latest.get('completed_by', {}).get('email', 'unknown'),
        'power_rating': None,
        'power_shift': None,
        'power_strategies': [],
        'validity': None,
        'notes': '',
    }

    for r in results:
        name = r.get('from_name', '')
        value = r.get('value', {})

        if name == 'power_rating':
            choices = value.get('choices', [])
            if choices:
                parsed['power_rating'] = choices[0]
        elif name == 'power_shift':
            choices = value.get('choices', [])
            if choices:
                parsed['power_shift'] = choices[0]
        elif name == 'power_strategies':
            parsed['power_strategies'] = value.get('choices', [])
        elif name == 'validity':
            choices = value.get('choices', [])
            if choices:
                parsed['validity'] = choices[0]
        elif name == 'notes':
            text_vals = value.get('text', [])
            if text_vals:
                parsed['notes'] = text_vals[0] if isinstance(text_vals, list) else text_vals

    return parsed


# ── Commands ───────────────────────────────────────────────────

def cmd_setup():
    """One-time setup: save API token and annotator name."""
    print()
    print("=== ANNOTATION SETUP ===")
    print()
    print("Before running this, you should have:")
    print("  1. Run 'label-studio start' at least once")
    print("  2. Created an account in the browser")
    print("  3. Gone to Account & Settings and copied your Access Token")
    print()

    name = input("Your name (e.g. nathan): ").strip().lower()
    token = input("Paste your Label Studio Access Token: ").strip()

    if not name or not token:
        print("ERROR: Both name and token are required.")
        return

    config = load_config()
    config['annotator_name'] = name
    config['api_token'] = token
    save_config(config)

    # Make sure .annotate_config.json is git-ignored
    gitignore_path = '.gitignore'
    ignore_entry = '.annotate_config.json'
    if os.path.exists(gitignore_path):
        with open(gitignore_path, 'r') as f:
            content = f.read()
        if ignore_entry not in content:
            with open(gitignore_path, 'a') as f:
                f.write(f"\n{ignore_entry}\n")
            print(f"  Added {ignore_entry} to .gitignore")
    else:
        with open(gitignore_path, 'w') as f:
            f.write(f"{ignore_entry}\n")
        print(f"  Created .gitignore with {ignore_entry}")

    print()
    print(f"Setup complete! Saved config for '{name}'.")
    print("You can now run: python annotate.py start")


def cmd_start():
    """Start an annotation session."""
    config = load_config()
    if 'api_token' not in config:
        print("ERROR: Run 'python annotate.py setup' first.")
        return

    token = config['api_token']
    name = config['annotator_name']

    print()
    print(f"=== STARTING ANNOTATION SESSION ({name}) ===")
    print()

    # Step 1: Git pull
    git_pull()

    # Step 2: Load source tasks
    if not os.path.exists(TASKS_SOURCE):
        print(f"  ERROR: {TASKS_SOURCE} not found.")
        print("  Run prepare_for_label_studio.py first.")
        return

    with open(TASKS_SOURCE, 'r', encoding='utf-8') as f:
        all_tasks = json.load(f)
    print(f"  Total documents in corpus: {len(all_tasks)}")

    # Step 3: Filter out already-annotated
    done_ids = load_already_annotated()
    available = [t for t in all_tasks if t['data']['doc_id'] not in done_ids]
    print(f"  Already annotated by team: {len(done_ids)}")
    print(f"  Available for annotation: {len(available)}")

    if not available:
        print("  All documents have been annotated!")
        return

    # Step 4: Randomly sample a batch
    random.seed(RANDOM_SEED_BASE + hash(name))
    random.shuffle(available)
    batch = available[:BATCH_SIZE]
    print(f"  Loading batch of {len(batch)} documents for this session.")

    # Step 5: Start Label Studio if not running
    if not ls_is_running(token):
        start_label_studio()

    # Verify token works
    if not ls_is_running(token):
        print("  ERROR: Can't connect to Label Studio with your token.")
        print("  Try running 'python annotate.py setup' again.")
        return

    # Step 6: Find or create project and import tasks
    project_id = find_or_create_project(token)
    config['project_id'] = project_id
    save_config(config)

    print(f"  Importing {len(batch)} documents into Label Studio...")
    import_tasks(project_id, batch, token)

    print()
    print("=" * 50)
    print("  READY! Open your browser to:")
    print(f"  {LS_URL}/projects/{project_id}")
    print()
    print('  Click "Label All Tasks" to start annotating.')
    print()
    print("  When you are done, run:")
    print("  python annotate.py finish")
    print("=" * 50)
    print()

    # Open browser
    import webbrowser
    webbrowser.open(f"{LS_URL}/projects/{project_id}")


def cmd_finish():
    """End an annotation session: export, merge, push."""
    config = load_config()
    if 'api_token' not in config:
        print("ERROR: Run 'python annotate.py setup' first.")
        return
    if 'project_id' not in config:
        print("ERROR: Run 'python annotate.py start' first.")
        return

    token = config['api_token']
    name = config['annotator_name']
    project_id = config['project_id']

    print()
    print(f"=== FINISHING ANNOTATION SESSION ({name}) ===")
    print()

    if not ls_is_running(token):
        print("  ERROR: Label Studio doesn't seem to be running.")
        print("  Make sure you haven't closed it before finishing.")
        return

    # Step 1: Export from Label Studio
    print("  Exporting annotations from Label Studio...")
    raw_export = export_annotations(project_id, token)

    if not raw_export:
        print("  No annotations found. Did you submit any?")
        return

    # Step 2: Parse into our format
    new_annotations = []
    for task in raw_export:
        parsed = parse_ls_annotation(task)
        if parsed and parsed['power_rating'] is not None:
            parsed['annotator'] = name
            new_annotations.append(parsed)

    if not new_annotations:
        print("  No completed annotations found.")
        print("  Make sure you clicked 'Submit' on each document.")
        return

    print(f"  Found {len(new_annotations)} completed annotations.")

    # Step 3: Pull latest (in case teammate pushed while you were annotating)
    git_pull()

    # Step 4: Merge into shared file
    total = save_annotations(new_annotations)
    print(f"  Merged into {SHARED_ANNOTATIONS} (total: {total} annotations)")

    # Step 5: Push
    git_push(name)

    print()
    print("=" * 50)
    print(f"  Done! Saved {len(new_annotations)} annotations.")
    print(f"  Team total: {total}")
    print("=" * 50)
    print()


def cmd_status():
    """Show annotation progress."""
    print()
    print("=== ANNOTATION STATUS ===")
    print()

    if not os.path.exists(TASKS_SOURCE):
        print(f"  {TASKS_SOURCE} not found. Run prepare_for_label_studio.py first.")
        return

    with open(TASKS_SOURCE, 'r', encoding='utf-8') as f:
        total = len(json.load(f))

    if os.path.exists(SHARED_ANNOTATIONS):
        with open(SHARED_ANNOTATIONS, 'r', encoding='utf-8') as f:
            annotations = json.load(f)

        # Count per annotator
        by_annotator = {}
        for a in annotations:
            name = a.get('annotator', 'unknown')
            by_annotator[name] = by_annotator.get(name, 0) + 1

        print(f"  Total documents: {total}")
        print(f"  Annotated:       {len(annotations)}")
        print(f"  Remaining:       {total - len(annotations)}")
        print()
        print("  Per annotator:")
        for name, count in sorted(by_annotator.items()):
            print(f"    {name}: {count}")
    else:
        print(f"  Total documents: {total}")
        print(f"  Annotated:       0")
        print(f"  Remaining:       {total}")

    print()


# ── Main ───────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print()
        print("Usage:")
        print("  python annotate.py setup    (one-time setup)")
        print("  python annotate.py start    (begin annotation session)")
        print("  python annotate.py finish   (save and push when done)")
        print("  python annotate.py status   (check team progress)")
        print()
        return

    command = sys.argv[1].lower()
    if command == 'setup':
        cmd_setup()
    elif command == 'start':
        cmd_start()
    elif command == 'finish':
        cmd_finish()
    elif command == 'status':
        cmd_status()
    else:
        print(f"Unknown command: {command}")
        print("Use: setup, start, finish, or status")


if __name__ == '__main__':
    main()